#!/bin/bash
# Generate TypeScript types from Rust using ts-rs
# Usage: ./scripts/generate-types.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Set export directory for ts-rs
export TS_RS_EXPORT_DIR="$PROJECT_ROOT/src/generated"

# Create output directory
mkdir -p "$TS_RS_EXPORT_DIR"

echo "Generating TypeScript types..."
echo "Output directory: $TS_RS_EXPORT_DIR"

# Run the export test to generate types
cd "$PROJECT_ROOT/src-tauri"
cargo test export_bindings --release -- --nocapture

# ts-rs generates separate files - combine into single bindings.ts
cd "$TS_RS_EXPORT_DIR"

# Create combined bindings file
cat > bindings.ts << 'EOF'
// Auto-generated by ts-rs from Rust types. Do not edit manually.
// Regenerate with: ./scripts/generate-types.sh

EOF

# Append each generated type file
for f in AppMode.ts Theme.ts LatencyThresholds.ts AppConfig.ts; do
    if [ -f "$f" ]; then
        cat "$f" >> bindings.ts
        echo "" >> bindings.ts
    fi
done

# Remove individual files (keep only combined bindings.ts)
rm -f AppMode.ts Theme.ts LatencyThresholds.ts AppConfig.ts

echo "TypeScript types generated successfully: $TS_RS_EXPORT_DIR/bindings.ts"
